// lib/main.dart
//
// WHAT:
// Has one job: initialize services and start the app.
// Business logic, navigation, theme — all go elsewhere.
// A bloated main.dart is a sign that architecture decisions were skipped.

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:firebase_core/firebase_core.dart';

import 'core/storage/cache_manager.dart';
import 'firebase_options.dart'; // generated by flutterfire configure
import 'app.dart';

void main() async {
  // Required before any async work in main()
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase (Analytics + Messaging)
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Initialise encrypted Hive offline cache
  // This must complete before the app builds — the cache
  // is used in repositories from the first frame
  await CacheManager.init();

  runApp(
    // ProviderScope is the Riverpod root.
    // Every provider in the app is accessible from here.
    // This wraps the ENTIRE widget tree — never put it inside a widget.
    const ProviderScope(
      child: SmartHealthApp(),
    ),
  );
}